simulation_files = files(
	'Air.cpp',
	'AccessProperty.cpp',
	'Element.cpp',
	'ElementClasses.cpp',
	'GOLString.cpp',
	'OmniBiology.cpp',
	'OmniChemistry.cpp',
	'OmniMetallurgy.cpp',
	'OmniNuclear.cpp',
	'OmniPeriodic.cpp',
	'Particle.cpp',
	'SaveRenderer.cpp',
	'Sign.cpp',
	'SimulationData.cpp',
	'Simulation.cpp',
	'StructProperty.cpp',
	'FrameTime.cpp',
)

subdir('elements')
subdir('simtools')
subdir('gravity')

powder_files += files(
	'AccessPropertyParse.cpp',
	'Editing.cpp',
	'SimTool.cpp',
	'ToolClasses.cpp',
	'Snapshot.cpp',
	'SnapshotDelta.cpp',
)
