#!/usr/bin/env python3

"""Apply the reviewed Simplified Chinese literal map to the Android source."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
CACHE = ROOT / "zh-cn-translation-cache.json"
SOURCE_SUFFIXES = {".cpp", ".h", ".lua"}
EXCLUDED_PARTS = {".git", "json", "updatepackager", "utility", "font"}
CPP_LITERAL = re.compile(r'"(?:\\.|[^"\\])*"')
SEMANTIC_LITERALS = {
    # Protocol, save-format, preference and scripting API tokens. These words
    # also occur in UI labels, but must never be replaced globally.
    "OK", "Error: ", "Saves", "Publish", "Error", "Favorite", "Favorites",
    "Favourite", "Favourites", "Decorations", "Fullscreen", "None", "none",
    "enabled", "gravity", "heat", "Gravity", "Temperature",
}

# The Android branch contains older and touch-only UI text that is absent from
# the desktop translation cache. Keep these reviewed overrides explicit so the
# localization can be reproduced without touching protocol keys or identifiers.
MOBILE_OVERRIDES = {
    "Animated Liquid Crystal. Can show multiple frames, use left/right in the deco editor.": "动画液晶。可显示多个帧；在装饰编辑器中使用左/右切换。",
    "Button. Can be sparked just by clicking on it, but only when turned on.": "按钮。开启后，只需点击即可产生火花。",
    "Explosion, causes everything it touches to explode.": "爆炸，会使接触到的一切发生爆炸。",
    "Force Emitter. Pushes or pulls objects based on it's temperature. Use like ARAY.": "力场发射器。根据温度推拉物体，用法类似 ARAY。",
    "Indestructible Insulator.": "不可摧毁的绝缘体。",
    "Isotope-Z. Radioactive liquid. Decays into photons when touching PHOT or under negative pressure.": "Z 同位素。放射性液体；接触 PHOT 或处于负压下会衰变成光子。",
    "More realistic lightning. Set pen size to set the size of the lightning.": "更真实的闪电。画笔大小决定闪电尺寸。",
    "Game Of Life: Begin 3/Stay 23": "康威生命游戏：出生 3 / 存活 23（B3/S23）",
    "Moving solid. Acts like a bouncy ball.": "移动固体。行为类似弹力球。",
    "Powered invisible,invisible to particles while activated.": "可控隐形材料，激活时粒子可穿过。",
    "Powered Portal OUT, can be turned on/off.": "可控出口传送门，可开启或关闭。",
    "Powered version of pipe": "可控管道。",
    "Powered Portal IN, can be turned on/off.": "可控入口传送门，可开启或关闭。",
    "Piston, pushes particles. PSCN extends, NSCN retracts.": "活塞，推动粒子。PSCN 伸出，NSCN 收回。",
    "Heavy silver particles, displaces everything.": "重质银粒子，可挤开一切。",
    "Powered Heater. Flood fill heats particles to its temp. Use only one.": "可控加热器。以洪水填充方式把粒子加热至自身温度；只需放置一个。",
    "Sponge, absorbs water. Is a moving solid.": "海绵，吸水。属于移动固体。",
    "Displaces other elements. Completely invisible.": "挤开其他元素，完全不可见。",
    "second stickman. Don't kill him! Control with wasd.": "第二个火柴人。别杀死他！使用 WASD 控制。",
    "Force Creating": "力场",
    "Game of Life": "生命游戏",
    "Favorites & Recents": "收藏与最近使用",
    "Deco": "装饰",
    "Other": "其他",
    "Search": "搜索",
    "Favorite2": "收藏",

    "Options": "设置",
    "Heat simulation": "热量模拟",
    "Causes unexpected behavior when disabled": "关闭后可能导致异常行为",
    "Ambient heat simulation": "环境热量模拟",
    "Heat transfers through empty space": "热量可穿过空白区域传递",
    "Newtonian Gravity": "牛顿引力",
    "Simulate local gravity fields": "模拟局部引力场",
    "Decorations": "装饰层",
    "Show deco color on elements": "在元素上显示装饰颜色",
    "Water Equalization": "水位平衡",
    "Water equalizes in a U-shaped pipe (lags game)": "水会在 U 形管中保持等高（可能卡顿）",
    "Pressure Off": "关闭压力",
    "Velocity Off": "关闭速度",
    "No Update": "暂停更新",
    "Air Simulation Mode:": "空气模拟模式：",
    "Ambient Air Temperature:": "环境空气温度：",
    "Ambient Air Pressure:": "环境空气压力：",
    "Ambient Air Velocity:": "环境空气速度：",
    "Vorticity Confinement:": "涡量约束：",
    "Air heat convection mode:": "空气热对流模式：",
    "Gravity Simulation Mode:": "引力模拟模式：",
    "Edge Mode:": "边界模式：",
    "Linear": "线性",
    "Gamma 2.2": "伽马 2.2",
    "Gamma 1.8": "伽马 1.8",
    "Smudge Tool Color Space:": "涂抹工具色彩空间：",
    "Temperature Scale:": "温标：",
    "Resizable Window": "可调整窗口大小",
    "Allow resizing window": "允许调整窗口大小",
    "Force Integer Scaling": "强制整数缩放",
    "Less Blurry": "画面更清晰",
    "Nearest": "最近邻",
    "Best": "最佳",
    "Pixel sampling mode:": "像素采样模式：",
    "Fill the entire screen": "填满整个屏幕",
    "Change Resolution": "更改分辨率",
    "Old fullscreen": "旧式全屏",
    "Fast Quit": "快速退出",
    r'Always exit completely when clicking \"X\"': "点击“X”时始终彻底退出",
    "Global Quit": "全局退出",
    "Update Check": "检查更新",
    "Check for updates at https://starcatcher.us/TPT": "从 https://starcatcher.us/TPT 检查更新",
    "Momentum Scrolling": "惯性滚动",
    "Acceleration instead of step scroll": "使用加速滚动而非逐格滚动",
    "Switch between menusections by clicking": "点击切换菜单分类",
    "Include Pressure": "保存压力",
    "Include pressure in saves and stamps": "在存档和图章中保存压力",
    "Perfect Circle Brush": "正圆画笔",
    "Key Under Esc Exits Console": "Esc 下方按键退出控制台",
    "Uncheck this if that key is 0 on your keyboard": "若该按键在键盘上输入 0，请取消勾选",
    "Load incompatible saves": "加载不兼容存档",
    "Saves from the future may load completely garbled": "较新版本的存档可能会完全错乱",
    "Open Data Folder": "打开数据目录",
    "Migration complete": "迁移完成",
    "These options make TPT appear extremely blurry": "这些选项会让 TPT 画面非常模糊",
    "Error, could not open data directory": "错误：无法打开数据目录",

    "Please wait": "请稍候",
    "Server did not return data": "服务器未返回数据",
    "Decompression failure: ": "解压失败：",
    "New sign:": "新建标牌：",
    "Edit sign:": "编辑标牌：",
    "\\xA0 Left": "\\xA0 左对齐",
    "\\x9E Middle": "\\x9E 居中",
    "\\x9F Right": "\\x9F 右对齐",
    "\\x9D None": "\\x9D 无指针",
    "\\x85 Delete": "\\x85 删除",
    "Edit Property:": "编辑属性：",
    "Invalid floating point number": "无效的浮点数",
    "Invalid element name": "无效的元素名称",
    "Invalid number": "无效的数字",
    "Duplicate name, cannot add": "名称重复，无法添加",

    "Sign In": "登录",
    "To manage your account (avatar, password, username, or delete it), \\bt{a:https://powdertoy.co.uk/Profile.html|Use the website}": "若要管理头像、密码、用户名或删除账号，请\\bt{a:https://powdertoy.co.uk/Profile.html|前往网站}",
    "If you don't have an account, \\bt{a:https://powdertoy.co.uk/Register.html|Register Here}": "没有账号？\\bt{a:https://powdertoy.co.uk/Register.html|在此注册}",
    "Please enter a username and password": "请输入用户名和密码",
    "Use your Powder Toy account to login, not your email. If you don't have a Powder Toy account, you can create one on \\bt{a:https://powdertoy.co.uk/Register.html|the website}": "请使用 Powder Toy 账号而非邮箱登录。没有账号可在\\bt{a:https://powdertoy.co.uk/Register.html|网站上注册}",
    "Successfully logged in": "登录成功",
    "Couldn't read login response": "无法读取登录响应",
    "Successfully logged out": "已退出登录",
    "Enable Editing": "启用编辑",
    "Open Profile Online": "在线打开个人资料",
    "\\x0F\\xC0\\xC0\\xC0Not Provided": "\\x0F\\xC0\\xC0\\xC0未提供",
    "\\brError parsing data from server": "\\br解析服务器数据失败",
    "\\brServer returned error": "\\br服务器返回错误",
    "Edit profile online": "在线编辑个人资料",

    "Adv.": "高级",
    "Simple": "简易",
    "Even more basic rendering - only elements and stickmen are rendered": "极简渲染：仅显示元素和火柴人",
    "Alternate Velocity display mode preset": "备用速度显示预设",
    "Vorticity display mode preset": "涡量显示预设",

    "Find & open a simulation": "查找并打开模拟",
    "Reload the simulation \\bg(ctrl+r)": "重新加载模拟 \\bg(Ctrl+R)",
    "\\x82 [untitled simulation]": "\\x82 [未命名模拟]",
    "Upload a new simulation": "上传新模拟",
    "\\xCB Vote": "\\xCB 投票",
    "Disike this save": "不喜欢此存档",
    "Pause the simulation \\bg(space)": "暂停模拟 \\bg(空格)",
    "\\x84 [sign in]": "\\x84 [登录]",
    "Sign into the Simulation Server": "登录模拟服务器",
    "Erase all particles and walls": "清除所有粒子和墙体",
    "Simulation options": "模拟设置",
    "Report bugs and feedback to jacob1": "向 jacob1 报告问题和反馈",
    "\\x83 [no tags set]": "\\x83 [未设置标签]",
    "Swap to erase tool (hold to clear the sim)": "切换到擦除工具（长按清空模拟）",
    "Open console (hold to show on screen keyboard)": "打开控制台（长按显示屏幕键盘）",
    "Toggle Decorations (hold to open options)": "切换装饰层（长按打开设置）",
    "Start placing the zoom window": "开始放置缩放窗口",
    "Save a stamp (hold to load a stamp)": "保存图章（长按加载图章）",
    "Error: a previous vote may not have gone through": "错误：上一次投票可能未成功提交",
    "Created local save. Hold ctrl and click open to access the local save browser": "已创建本地存档。按住 Ctrl 并点击打开按钮可进入本地存档浏览器",
    "Created local save. Hold down the open button to access the local save browser": "已创建本地存档。长按打开按钮可进入本地存档浏览器",
    "Error writing local save": "写入本地存档失败",
    "Updated successfully": "更新成功",
    "Saved successfully": "保存成功",
    "Saved successfully!": "保存成功！",
    "Error saving": "保存失败",
    "Error: could not vote": "错误：无法投票",
    "Cleared the simulation": "已清空模拟",
    "Erase tool deselected": "已取消擦除工具",
    "Erase tool selected": "已选择擦除工具",
    "Decorations enabled": "装饰层已开启",
    "Decorations disabled": "装饰层已关闭",
    "\\bwDo you want to update TPT?": "\\bw是否更新 TPT？",
    "\\btUpdate": "\\bt更新",
    "Error reloading save": "重新加载存档失败",
    "A new version is available - click here!": "有新版本可用——点击查看！",
    "Error, the update server returned invalid data": "错误：更新服务器返回了无效数据",
    "Cleared Vote": "已清除投票",
    "Voted Successfully": "投票成功",
    "Sign limit reached": "已达到标牌数量上限",
    "[save to disk]": "[保存到本机]",
    "Save the simulation to your hard drive": "将模拟保存到本机",
    "Add and remove simulation tags": "添加或移除模拟标签",
    "View and edit your profile": "查看并编辑个人资料",
    "You're a moderator": "你是版主",
    "Sign into the simulation server under a new name": "使用其他名称登录模拟服务器",
    "Could not validate login": "无法验证登录状态",
    "Waiting for login server ...": "正在等待登录服务器……",
    "Resume the simulation \\bg(space)": "继续模拟 \\bg(空格)",
    "Open a simulation from your hard drive \\bg(ctrl+o)": "从本机打开模拟 \\bg(Ctrl+O)",
    "Quit": "退出",
    "Saved screenshot": "截图已保存",
    "Error saving screenshot": "截图保存失败",
    "Save authorship info": "保存作者信息",
    "Decorations layer: On": "装饰层：开",
    "Decorations layer: Off": "装饰层：关",
    "Dynamic heat mode: On": "动态热量模式：开",
    "Dynamic heat mode: Off": "动态热量模式：关",
    "Dropped file is not a TPT save file. Must have a .cps or .stm extension": "拖入的文件不是 TPT 存档，扩展名必须为 .cps 或 .stm",
    "Error loading save: ": "加载存档失败：",
    "Error creating save: ": "创建存档失败：",
    "Exception while translating stamp: ": "转换图章版本时发生异常：",
    "Exception while transforming stamp: ": "变换图章时发生异常：",
    "Error building save: ": "生成存档失败：",
    r"Links: \bt{a:https://powdertoy.co.uk|Powder Toy main page}\bg, \bt{a:https://powdertoy.co.uk/Discussions/Categories/Index.html|Forums}\bg, \bt{a:https://github.com/The-Powder-Toy/The-Powder-Toy|Official TPT github}\bg, \bt{a:https://github.com/jacob1/The-Powder-Toy/tree/c++|Jacob1\'s Mod github}": r"链接：\bt{a:https://powdertoy.co.uk|Powder Toy 主页}\bg，\bt{a:https://powdertoy.co.uk/Discussions/Categories/Index.html|论坛}\bg，\bt{a:https://github.com/The-Powder-Toy/The-Powder-Toy|TPT 官方 GitHub}\bg，\bt{a:https://github.com/jacob1/The-Powder-Toy/tree/c++|Jacob1 模组 GitHub}",
    "\\bbYour version: ": "\\bb当前版本：",
    "New version: ": "新版本：",
    "\\n\\n\\bwChangeLog:\\n": "\\n\\n\\bw更新日志：\\n",
    " required": "（所需）",
    "\\x0F\\xFF\\x01\\x01\\x84\\x0E [sign in]": "\\x0F\\xFF\\x01\\x01\\x84\\x0E [登录]",
    r"\x0F\xEF\xEF\020Tap any location to place a zoom window (volume keys to resize, click zoom button to cancel)": r"\x0F\xEF\xEF\020轻触任意位置放置缩放窗口（音量键调整大小，点击缩放按钮取消）",
    r"\x0F\xEF\xEF\020Click-and-drag to specify a rectangle to copy (click save button to cancel)": r"\x0F\xEF\xEF\020拖动选取要复制的矩形区域（点击保存按钮取消）",
    r"\x0F\xEF\xEF\020Click-and-drag to specify a rectangle to copy and then cut (click save button to cancel)": r"\x0F\xEF\xEF\020拖动选取要复制并剪切的矩形区域（点击保存按钮取消）",
    r"\x0F\xEF\xEF\020Drag the stamp around to move it, and tap it to place. Tap or drag outside the stamp to shift and rotate.": r"\x0F\xEF\xEF\020拖动图章可移动，轻触图章可放置；在图章外轻触或拖动可平移和旋转。",
    r"\x0F\xEF\xEF\020Click-and-drag to specify a rectangle to copy (right click = cancel)": r"\x0F\xEF\xEF\020拖动选取要复制的矩形区域（右键取消）",
    r"\x0F\xEF\xEF\020Click-and-drag to specify a rectangle to copy and then cut (right click = cancel)": r"\x0F\xEF\xEF\020拖动选取要复制并剪切的矩形区域（右键取消）",
    "Install Powder Toy": "安装 Powder Toy",
    "You are about to install The Powder Toy": "即将安装 The Powder Toy",
    "Install": "安装",
    "Install Success": "安装成功",
    "Powder Toy has been installed!": "Powder Toy 已安装！",
    "Install failed - You may not have permission or you may be on a platform that does not support installation": "安装失败：可能没有权限，或当前平台不支持安装",
    "Experimental old menu activated, press 'o' to turn off": "实验性旧菜单已启用，按 O 关闭",

    "Are you sure you want to quit?": "确定要退出吗？",
    "An unrecoverable fault has occurred, please report this to jacob1:\\n": "发生了无法恢复的错误，请向 jacob1 报告：\\n",
    " OR the built in bug reporter.\\n\\n": " 或使用内置问题报告器。\\n\\n",
    "Note: TPT will now restart and reload your work": "注意：TPT 现在将重启并重新加载当前作品",
    "ERROR": "错误",
    "Score: %i": "得分：%i",

    "set color": "设置颜色",
    "subtract color": "减去颜色",
    "no effect": "无效果",
    "PHOT scatter": "PHOT 散射",
    "unknown mode": "未知模式",
    "Ctype: ": "Ctype：",
    "Temp: %s, ": "温度：%s，",
    "Life: %d, ": "寿命：%d，",
    "Tmp: %d, ": "Tmp：%d，",
    "Tmp2: %d, ": "Tmp2：%d，",
    "Dcolor: 0x%.8X, ": "装饰色：0x%.8X，",
    "Flags: 0x%.8X, ": "标志：0x%.8X，",
    "Empty, ": "空白，",
    "Pressure: %0.*f, ": "压力：%0.*f，",
    "Version %d.%d (%d) ": "版本 %d.%d（%d） ",
    "Version %d.%d ": "版本 %d.%d ",
    "Build %d ": "构建 %d ",
    "Parts: %d/%d ": "粒子：%d/%d ",
    "Parts: %d ": "粒子：%d ",
    "Generation:%d ": "世代：%d ",
    "Gravity:%d ": "引力：%d ",
    "Air:%d ": "空气：%d ",
    "Time Played: %s ": "本次时长：%s ",
    "Total Time Played: %s ": "总时长：%s ",
    "Average FPS: %0.*f ": "平均帧率：%0.*f ",
    "[REPLACE MODE] ": "[替换模式] ",
    "[SPECIFIC DELETE] ": "[指定删除] ",
    "[FIND] ": "[查找] ",
    "[GRID: %d] ": "[网格：%d] ",
    "[Frame %i/%i] ": "[帧 %i/%i] ",

    "Android version ": "Android 版本 ",
    r"\bgTouch and drag the menus on the right side to show each menusection.\n": r"\bg触摸并拖动右侧菜单可显示各个分类。\n",
    r"For scrollable menusections, the menus can be dragged around.\n": r"可滚动的分类菜单可直接拖动浏览。\n",
    r"Use the volume keys to change the tool size for particles.\n": r"使用音量键调整粒子工具大小。\n",
    r"To open online saves, tap the 'Find & open a simulation' button on the very bottom left.\n": r"要打开在线存档，请点击左下角的“查找并打开模拟”按钮。\n",
    r"To pause and unpause the game, use the pause button on the very bottom right.\n\n": r"使用右下角暂停按钮可暂停或继续游戏。\n\n",
    r"\boThe buttons on the right do the following actions respectively:\n": r"\bo右侧按钮依次执行以下操作：\n",
    r"\bo   Toggle erase tool (hold button down to clear screen)\n": r"\bo   切换擦除工具（长按清屏）\n",
    r"\bo   Open the console (hold button to show the on screen keyboard)\n": r"\bo   打开控制台（长按显示屏幕键盘）\n",
    r"\bo   Toggle Newtonian gravity, or decorations while in deco menu (hold to open simulation settings)\n": r"\bo   切换牛顿引力；在装饰菜单中切换装饰层（长按打开模拟设置）\n",
    r"\bo   Place or remove a zoom window\n": r"\bo   放置或移除缩放窗口\n",
    r"\bo   Save a stamp (hold to load a stamp)\n\n": r"\bo   保存图章（长按加载图章）\n\n",
    r"\boWhen placing a stamp, you may do the following:\n": r"\bo放置图章时可以：\n",
    r"\bo   Drag the stamp around wherever you want.\n": r"\bo   将图章拖到任意位置。\n",
    r"\bo   Tap the stamp without moving it to place.\n": r"\bo   轻触图章且不移动即可放置。\n",
    r"\bo   Touch any location outside of the stamp to shift it by one pixel.\n": r"\bo   轻触图章外任意位置可平移一个像素。\n",
    r"\bo   Rotate the stamp by first tapping around the edges and then dragging in a circle.\n": r"\bo   先轻触边缘，再沿圆周拖动即可旋转图章。\n",
    r"\bgTo use online features such as saving, you need to register at: \brhttps://powdertoy.co.uk/Register.html\n": r"\bg要使用在线保存等功能，请先注册：\brhttps://powdertoy.co.uk/Register.html\n",

    "Feedback": "反馈",
    "Report details": "报告详情",
    "Send": "发送",
    "Feedback has been sent": "反馈已发送",
    "This save has been reported": "已举报此存档",
    "Add comment": "添加评论",
    "Save data is empty (may be corrupt)": "存档数据为空（可能已损坏）",
    "Save info not found": "未找到存档信息",
    "Failed to parse save info": "解析存档信息失败",
    "Save doesn't exist": "存档不存在",
    "Author: ": "作者：",
    "Author:": "作者：",
    "Updated:": "更新于：",
    "Created:": "创建于：",
    "Views:": "浏览：",
    "Page %i of %i": "第 %i 页，共 %i 页",
    "Save ID: ": "存档 ID：",
    "Unfav.": "取消收藏",
    "Fav.": "收藏",
    "Open in Browser": "在浏览器中打开",
    "Removing from favourites...": "正在取消收藏……",
    "Adding to favourites...": "正在加入收藏……",
    "Are you sure you wish to delete this?": "确定要删除吗？",
    "You will not be able recover it.": "删除后无法恢复。",
    "Deleting...": "正在删除……",
    "Save permanently deleted": "存档已永久删除",
    "Submitting Comment...": "正在提交评论……",
    "Downloading": "正在下载",
    "An error occurred when parsing the save: ": "解析存档时发生错误：",
    "Loading": "正在加载",
    "Cannot publish save, incompatible with latest release version.": "无法发布：存档与最新正式版不兼容。",
    "Could not save - no reply from server": "保存失败：服务器未响应",
    "No ID supplied by server": "服务器未提供 ID",
    "Unspecified Error": "未指定错误",
    "Could not read response: ": "无法读取响应：",
    "Clear": "清除",
    "Reset Decoration Layer": "重置装饰层",
    "Do you really want to erase everything?": "确定要擦除全部装饰吗？",
    "Erase": "擦除",
    "Copied to clipboard": "已复制到剪贴板",
    "Filename:": "文件名：",
    "A save with that name already exists.": "已存在同名存档。",
    "Overwrite": "覆盖",
    "Unable to write to save file.": "无法写入存档文件。",
    "Found %d save%s": "找到 %d 个存档%s",
    "Saves": "存档",
    "Unable to load save: ": "无法加载存档：",
    "Unable to read save file": "无法读取存档文件",
    "Do you want to delete?": "确定要删除吗？",
    "This save uses custom elements that are not currently available.": "此存档使用了当前不可用的自定义元素。",
    "This save uses custom elements that are not currently available. Make sure that you use the mod and/or have all the scripts the save requires to fully load": "此存档使用了当前不可用的自定义元素。请确认已安装对应模组及存档所需的全部脚本。",
    "HTTP error:": "HTTP 错误：",
    "Error:": "错误：",
    "[element name]": "[元素名称]",
    "\\xE6 Element Search": "\\xE6 元素搜索",
    "Matches:": "匹配项：",
    "Related:": "相关项：",
    "Use 's' to save stamps": "按 S 保存图章",
    "You haven't created any stamps yet": "尚未创建任何图章",
    "Couldn't rename, stamp with that name already exists": "无法重命名：已存在同名图章",
    "Rescanning ...": "正在重新扫描……",
    " - voted!": " - 已赞成！",
    " - voted.": " - 已反对。",
    "Not Authenticated": "尚未登录",
    "[simulation name]": "[模拟名称]",
    "Warning: uses mod elements, cannot publish": "警告：使用了模组元素，无法发布",
    "Publish?": "发布？",
    "Paused?": "已暂停？",
    "Save simulation": "保存模拟",
    "Current save ID: ": "当前存档 ID：",
    "\\bgPress 'o' to return to the original menu": "\\bg按 O 返回原菜单",
    "Lua console not enabled": "Lua 控制台未启用",
    "# of Decimal places must be between 0 and 10": "小数位数必须在 0 到 10 之间",
    "[search terms], click search icon for help": "[搜索] 点击图标查看帮助",
    "[search terms], press F1 for help": "[搜索] 按 F1 查看帮助",
    "of ": "共 ",
    "\\x96 Prev": "\\x96 上一页",
    "Next \\x95": "下一页 \\x95",
    "Popular tags:": "热门标签：",
    "Loading ...": "正在加载……",
    "Delete Saves": "删除存档",
    "Unpublish Saves": "取消发布存档",
    "Publish Saves": "发布存档",
    "Favorite Saves": "收藏存档",
    "Failed to perform action, cannot allocate memory": "操作失败：无法分配内存",
    "Report bugs and feedback here. Do not suggest new elements or features, or report bugs with downloaded scripts.": "请在此报告问题和反馈。请勿建议新元素或功能，也不要报告下载脚本的问题。",
}


def source_files():
    for path in ROOT.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in SOURCE_SUFFIXES:
            continue
        relative = path.relative_to(ROOT)
        if any(part in EXCLUDED_PARTS for part in relative.parts):
            continue
        yield path


def main() -> None:
    translations = json.loads(CACHE.read_text(encoding="utf-8"))
    translations.update(MOBILE_OVERRIDES)
    translations = {
        source: target
        for source, target in translations.items()
        if source != target
        and source not in SEMANTIC_LITERALS
        and re.search(r"[\u3400-\u9fff]", target)
    }

    changed_files = 0
    replacements = 0
    for path in source_files():
        text = path.read_text(encoding="utf-8")
        updated = text
        literals = {match.group(0)[1:-1] for match in CPP_LITERAL.finditer(text)}
        for source in sorted(literals & translations.keys(), key=len, reverse=True):
            target = re.sub(r'(?<!\\)"', r'\\"', translations[source])
            old = f'"{source}"'
            count = updated.count(old)
            if count:
                updated = updated.replace(old, f'"{target}"')
                replacements += count
        if updated != text:
            path.write_text(updated, encoding="utf-8", newline="")
            changed_files += 1

    print(f"{replacements} literal replacements in {changed_files} files")


if __name__ == "__main__":
    main()
