from __future__ import annotations

from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[2]
RUNNER = (ROOT / "tools" / "run_atmospherebench.ps1").read_text(encoding="utf-8")


class AtmosphereBenchRunnerContractTests(unittest.TestCase):
    def test_runner_requires_clean_source_and_strict_build_flags(self) -> None:
        self.assertIn("requires a clean source worktree", RUNNER)
        self.assertIn("-fno-fast-math", RUNNER)
        self.assertIn("-ffp-contract=off", RUNNER)
        self.assertIn("/fp:strict", RUNNER)
        self.assertIn("inherited a Legacy fast-math flag", RUNNER)

    def test_runner_rebuilds_and_binds_the_build_tree_to_current_source(self) -> None:
        self.assertIn('"compile" "-C" $resolvedBuildDirectory "atmospherebench"', RUNNER)
        self.assertIn("build directory is configured from a different source root", RUNNER)
        self.assertIn("compile commands are not bound to current source", RUNNER)
        self.assertIn("tools/atmospherebench/Rusanov1D.cpp", RUNNER)
        self.assertIn("tools/atmospherebench/Species2D.cpp", RUNNER)
        self.assertIn("tools/atmospherebench/LbmD2Q9.cpp", RUNNER)
        self.assertIn("rebuilt_before_measurement = $true", RUNNER)
        self.assertIn("source_root_verified = $true", RUNNER)

    def test_runner_executes_only_the_unique_meson_target_output(self) -> None:
        self.assertIn('"introspect" "--targets" $resolvedBuildDirectory', RUNNER)
        self.assertIn('$_.name -eq "atmospherebench"', RUNNER)
        self.assertIn("AtmosphereBench Meson target must resolve uniquely", RUNNER)
        self.assertIn("Requested executable does not match the freshly built AtmosphereBench Meson target", RUNNER)
        self.assertIn("meson_target_output = $resolvedExecutable", RUNNER)

    def test_runner_records_its_explicit_git_provenance(self) -> None:
        self.assertIn("[string] $GitExecutable = \"git\"", RUNNER)
        self.assertIn("git_executable = $gitCommand", RUNNER)
        self.assertIn("git_sha256 = Get-Sha256 -Path $gitCommand", RUNNER)

    def test_runner_hashes_source_state_on_windows_powershell_5_1(self) -> None:
        self.assertIn("function Get-TextSha256", RUNNER)
        self.assertIn("SHA256Managed", RUNNER)
        self.assertIn("ComputeHash($bytes)", RUNNER)
        self.assertNotIn("SHA256]::HashData", RUNNER)
        self.assertNotIn("$buildSystemFiles = @(", RUNNER)
        self.assertNotIn("$targets = @($targetsText", RUNNER)

    def test_runner_rechecks_source_after_measurement(self) -> None:
        self.assertIn("$finalSourceState = Get-SourceState", RUNNER)
        self.assertIn("source changed during build or measurement", RUNNER)
        self.assertIn("source_stable_through_measurement = $true", RUNNER)

    def test_runner_records_unselected_contract_only_status(self) -> None:
        self.assertIn("not_evaluated_contract_only", RUNNER)
        self.assertIn("$candidateImplementations = \"none\"", RUNNER)
        self.assertIn("standalone_contract_uniform_no_solver_step", RUNNER)
        self.assertIn("artifacts/vnext-atmospherebench", RUNNER)

    def test_runner_has_an_explicit_rusanov_probe_mode(self) -> None:
        self.assertIn("[switch] $RunRusanovUniform", RUNNER)
        self.assertIn("[switch] $RunRusanovPressurePulse", RUNNER)
        self.assertIn("[switch] $RunRusanovDensityAdvection", RUNNER)
        self.assertIn("[switch] $RunRusanovContactDiscontinuity", RUNNER)
        self.assertIn("[switch] $RunRusanovNearVacuumExpansion", RUNNER)
        self.assertIn("[switch] $RunRusanovSodShockTube", RUNNER)
        self.assertIn("--run-rusanov-uniform", RUNNER)
        self.assertIn("--run-rusanov-pressure-pulse", RUNNER)
        self.assertIn("--run-rusanov-density-advection", RUNNER)
        self.assertIn("--run-rusanov-contact-discontinuity", RUNNER)
        self.assertIn("--run-rusanov-near-vacuum-expansion", RUNNER)
        self.assertIn("--run-rusanov-sod-shock-tube", RUNNER)
        self.assertIn("[switch] $RunRusanovDensityAdvectionRefinement", RUNNER)
        self.assertIn("--run-rusanov-density-advection-refinement", RUNNER)
        self.assertIn("[switch] $RunRusanovLowMachAdvection", RUNNER)
        self.assertIn("--run-rusanov-low-mach-advection", RUNNER)
        self.assertIn("[switch] $RunAllSpeedRusanovLowMachAdvection", RUNNER)
        self.assertIn("--run-all-speed-rusanov-low-mach-advection", RUNNER)
        self.assertIn("[switch] $RunHllcRusanovFallbackLowMachAdvection", RUNNER)
        self.assertIn("--run-hllc-rusanov-fallback-low-mach-advection", RUNNER)
        self.assertIn("[switch] $RunHllcRusanovFallbackNearVacuumExpansion", RUNNER)
        self.assertIn("--run-hllc-rusanov-fallback-near-vacuum-expansion", RUNNER)
        self.assertIn("[switch] $RunHllcRusanovFallbackSodShockTube", RUNNER)
        self.assertIn("--run-hllc-rusanov-fallback-sod-shock-tube", RUNNER)
        self.assertIn("[switch] $RunHllcRusanovFallbackOpenBoundaryLeak", RUNNER)
        self.assertIn("--run-hllc-rusanov-fallback-open-boundary-leak", RUNNER)
        self.assertIn("[switch] $RunHllcRusanovFallbackPerformance", RUNNER)
        self.assertIn("--run-hllc-rusanov-fallback-performance", RUNNER)
        self.assertIn("[switch] $RunHllc2DUniform", RUNNER)
        self.assertIn("--run-hllc-2d-uniform", RUNNER)
        self.assertIn("[switch] $RunHllc2DPressurePulse", RUNNER)
        self.assertIn("--run-hllc-2d-pressure-pulse", RUNNER)
        self.assertIn("[switch] $RunHllc2DSealedHeating", RUNNER)
        self.assertIn("--run-hllc-2d-sealed-heating", RUNNER)
        self.assertIn("[switch] $RunHllc2DNaturalConvection", RUNNER)
        self.assertIn("--run-hllc-2d-natural-convection", RUNNER)
        self.assertIn("[switch] $RunHllc2DSpeciesMixing", RUNNER)
        self.assertIn("--run-hllc-2d-species-mixing", RUNNER)
        self.assertIn("[switch] $RunHllc2DPerformance", RUNNER)
        self.assertIn("--run-hllc-2d-performance", RUNNER)
        self.assertIn("[switch] $RunLbmD2Q9Uniform", RUNNER)
        self.assertIn("--run-lbm-d2q9-uniform", RUNNER)
        self.assertIn("[switch] $RunLbmD2Q9ShearWave", RUNNER)
        self.assertIn("--run-lbm-d2q9-shear-wave", RUNNER)
        self.assertIn("[switch] $RunRusanovOpenBoundaryLeak", RUNNER)
        self.assertIn("--run-rusanov-open-boundary-leak", RUNNER)
        self.assertIn("[switch] $RunRusanovPerformance", RUNNER)
        self.assertIn("--run-rusanov-performance", RUNNER)
        self.assertIn("[switch] $RunHybridMixedRegion2D", RUNNER)
        self.assertIn("--run-hybrid-mixed-region-2d", RUNNER)
        self.assertIn("atmospherebench_hybrid_mixed_region_2d_probe", RUNNER)
        self.assertIn("physical_acoustic_domain_cells", RUNNER)
        self.assertIn("route_scan_only_not_solver_throughput", RUNNER)
        self.assertIn("atmospherebench_rusanov_uniform_probe", RUNNER)
        self.assertIn("atmospherebench_rusanov_pressure_pulse_probe", RUNNER)
        self.assertIn("atmospherebench_rusanov_density_advection_probe", RUNNER)
        self.assertIn("atmospherebench_rusanov_contact_discontinuity_probe", RUNNER)
        self.assertIn("atmospherebench_rusanov_near_vacuum_expansion_probe", RUNNER)
        self.assertIn("atmospherebench_rusanov_sod_shock_tube_probe", RUNNER)
        self.assertIn("atmospherebench_rusanov_density_advection_refinement_probe", RUNNER)
        self.assertIn("atmospherebench_rusanov_low_mach_advection_probe", RUNNER)
        self.assertIn("atmospherebench_rusanov_open_boundary_leak_probe", RUNNER)
        self.assertIn("atmospherebench_rusanov_performance_probe", RUNNER)
        self.assertIn("not_evaluated_candidate_probe", RUNNER)
        self.assertIn("candidate_implementations = $candidateImplementations", RUNNER)
        self.assertIn("Rusanov probe must not claim solver selection", RUNNER)
        self.assertIn("first-order strict-double 1D periodic uniform probe", RUNNER)
        self.assertIn("pressure-pulse did not produce a measurable state evolution", RUNNER)
        self.assertIn("pressure_peak_reduced", RUNNER)
        self.assertIn("state_change_l1", RUNNER)
        self.assertIn("density_l1_error", RUNNER)
        self.assertIn("advection_reference_passed", RUNNER)
        self.assertIn("density_bounds_preserved", RUNNER)
        self.assertIn("near-vacuum density did not remain positive and near-vacuum", RUNNER)
        self.assertIn("near-vacuum pressure did not remain positive and near-vacuum", RUNNER)
        self.assertIn("near-vacuum expansion did not transfer mass into the low-density region", RUNNER)
        self.assertIn("Sod boundary-adjusted ledger exceeds tolerance", RUNNER)
        self.assertIn("Sod wall-pressure impulse was not recorded", RUNNER)
        self.assertIn("state_and_flux_scratch_bytes_total", RUNNER)
        self.assertIn("source_ledger_closes", RUNNER)
        self.assertIn("conservative_source_ledger", RUNNER)
        self.assertIn("sealed-heating energy source did not reconcile", RUNNER)
        self.assertIn("natural-convection circulation signal is below", RUNNER)
        self.assertIn("species-mixing composition did not evolve with a measurable TV decrease", RUNNER)
        self.assertIn("species_ledger_closes", RUNNER)
        self.assertIn("species_bounds_preserved", RUNNER)
        self.assertIn("physical_diffusion", RUNNER)
        self.assertIn("species_mixing = $speciesMixing", RUNNER)
        self.assertIn("HLLC 2D performance metric is invalid", RUNNER)
        self.assertIn("performance_budget_status", RUNNER)
        self.assertIn("hllc_2d_performance = $hllc2DPerformance", RUNNER)
        self.assertIn("LBM D2Q9 shear-wave decay error exceeds tolerance", RUNNER)
        self.assertIn("not_applicable_no_energy_state", RUNNER)
        self.assertIn("lbm_d2q9 = $lbmD2Q9", RUNNER)
        self.assertIn("Legacy-like pressure pulse did not evolve through the control stencil", RUNNER)
        self.assertIn("not_applicable_no_mass_state", RUNNER)
        self.assertIn("legacy_like = $legacyLike", RUNNER)
        self.assertIn("if ($isLegacyLikeProbe) { $null }", RUNNER)
        self.assertIn("not production Legacy Air equivalence", RUNNER)
        self.assertIn("Hybrid policy probe must not claim solver selection", RUNNER)
        self.assertIn("cross-route boundary coupling", RUNNER)
        self.assertIn("hybrid_policy = $hybridPolicy", RUNNER)
        self.assertIn("source_and_boundary_ledger_closes", RUNNER)
        self.assertIn("boundary_exchange_ledger", RUNNER)
        self.assertIn('"eos_gamma" = "1.4"', RUNNER)
        self.assertIn("TPT wall-coupling", RUNNER)
        self.assertIn("refinement observed order is outside", RUNNER)
        self.assertIn("low-Mach characterization did not expose increasing diffusion", RUNNER)
        self.assertIn("low-Mach suitability result is invalid", RUNNER)
        self.assertIn("open-boundary leak did not record positive mass outflow", RUNNER)
        self.assertIn("open-boundary leak ledger exceeds tolerance", RUNNER)
        self.assertIn("sealed_left_open_right_reservoir", RUNNER)
        self.assertIn("recorded_candidate_measurement_no_budget", RUNNER)
        self.assertIn("Rusanov performance metric is invalid", RUNNER)
        self.assertIn('} else {\n\t"contract_uniform"', RUNNER)
        self.assertIn("Select only one AtmosphereBench run mode", RUNNER)
        self.assertIn("state_evolved = $stateEvolved", RUNNER)
        self.assertIn("pressure_peak_reduced = $pressurePeakReduced", RUNNER)
        self.assertIn("[double]::IsNaN($maximumCfl)", RUNNER)
        self.assertIn("[double]::IsInfinity($maximumCfl)", RUNNER)
        self.assertIn('candidate=fvm_hlle|status=registered_only|solver_implemented=false', RUNNER)
        self.assertIn('candidate=lbm_d2q9|status=implemented_isothermal_uniform_shear_wave_only|solver_implemented=true', RUNNER)
        self.assertIn('candidate=legacy_like|status=implemented_dimensionless_uniform_pressure_pulse_control_only|solver_implemented=true', RUNNER)
        self.assertIn('candidate=hybrid_all_speed_components|status=implemented_uncoupled_low_mach_transport_and_whole_case_hllc_sod_policy_probe_not_solver|solver_implemented=false', RUNNER)
        self.assertIn('candidate=hybrid_all_speed_mixed_region_probe|status=implemented_1d_router_cross_route_reflux_event_local_probe_not_solver_selection|solver_implemented=false', RUNNER)
        self.assertIn('candidate=fvm_all_speed_rusanov|status=implemented_1d_low_mach_probe_rejected|solver_implemented=true', RUNNER)
        self.assertIn('candidate=fvm_hllc_rusanov_fallback|status=implemented_1d_low_mach_near_vacuum_sod_open_leak_performance_and_2d_uniform_pressure_pulse_sealed_heating_natural_convection_species_mixing_performance_probes|solver_implemented=true', RUNNER)

    def test_runner_rejects_a_dimensional_or_stepped_scaffold_case(self) -> None:
        self.assertIn("must keep the shared case nondimensional", RUNNER)
        self.assertIn("must not claim a solver step", RUNNER)
        self.assertIn("shared grid contract drifted", RUNNER)
        self.assertIn("state_bytes_per_cell", RUNNER)
        self.assertIn("numerical_correction_ledger", RUNNER)
        self.assertIn("correction_energy_removed", RUNNER)
        self.assertIn("correction_event_count", RUNNER)

    def test_runner_has_no_production_client_launch_or_legacy_air_binding(self) -> None:
        forbidden = ("tpt-zh-omnipack", "updateUpTo", "Air.cpp", "Simulation.cpp", "LuaScriptInterface")
        for needle in forbidden:
            with self.subTest(needle=needle):
                self.assertNotIn(needle, RUNNER)


if __name__ == "__main__":
    unittest.main()
