simulation_elem_names = [
	'NONE',
	'DUST',
	'WATR',
	'OIL',
	'FIRE',
	'STNE',
	'LAVA',
	'GUNP',
	'NITR',
	'CLNE',
	'GAS',
	'PLEX',
	'GOO',
	'ICEI',
	'METL',
	'SPRK',
	'SNOW',
	'WOOD',
	'NEUT',
	'PLUT',
	'PLNT',
	'ACID',
	'VOID',
	'WTRV',
	'CNCT',
	'DSTW',
	'SALT',
	'SLTW',
	'DMND',
	'BMTL',
	'BRMT',
	'PHOT',
	'URAN',
	'WAX',
	'MWAX',
	'PSCN',
	'NSCN',
	'LNTG',
	'INSL',
	'BHOL',
	'WHOL',
	'RBDM',
	'LRBD',
	'NTCT',
	'SAND',
	'GLAS',
	'PTCT',
	'BGLA',
	'THDR',
	'PLSM',
	'ETRD',
	'NICE',
	'NBLE',
	'BTRY',
	'LCRY',
	'STKM',
	'SWCH',
	'SMKE',
	'DESL',
	'COAL',
	'LO2',
	'O2',
	'INWR',
	'YEST',
	'DYST',
	'THRM',
	'GLOW',
	'BRCK',
	'CFLM',
	'FIRW',
	'FUSE',
	'FSEP',
	'AMTR',
	'BCOL',
	'PCLN',
	'HSWC',
	'IRON',
	'MORT',
	'LIFE',
	'DLAY',
	'CO2',
	'DRIC',
	'CBNW',
	'STOR',
	'PVOD',
	'CONV',
	'CAUS',
	'LIGH',
	'TESC',
	'DEST',
	'SPNG',
	'RIME',
	'FOG',
	'BCLN',
	'LOVE',
	'DEUT',
	'WARP',
	'PUMP',
	'FWRK',
	'PIPE',
	'FRZZ',
	'FRZW',
	'GRAV',
	'BIZR',
	'BIZRG',
	'BIZRS',
	'INST',
	'ISOZ',
	'ISZS',
	'PRTI',
	'PRTO',
	'PSTE',
	'PSTS',
	'ANAR',
	'VINE',
	'INVIS',
	'E116',
	'SPAWN2',
	'SPAWN',
	'SHLD1',
	'SHLD2',
	'SHLD3',
	'SHLD4',
	'LOLZ',
	'WIFI',
	'FILT',
	'ARAY',
	'BRAY',
	'STKM2',
	'BOMB',
	'C5',
	'SING',
	'QRTZ',
	'PQRT',
	'EMP',
	'BREC',
	'ELEC',
	'ACEL',
	'DCEL',
	'BANG',
	'IGNT',
	'BOYL',
	'GEL',
	'TRON',
	'TTAN',
	'EXOT',
	disabler(),
	'EMBR',
	'H2',
	'SOAP',
	'NBHL',
	'NWHL',
	'MERC',
	'PBCN',
	'GPMP',
	'CLST',
	'WIRE',
	'GBMB',
	'FIGH',
	'FRAY',
	'RPEL',
	'PPIP',
	'DTEC',
	'DMG',
	'TSNS',
	'VIBR',
	'BVBR',
	'CRAY',
	'PSTN',
	'FRME',
	'GOLD',
	'TUNG',
	'PSNS',
	'PROT',
	'VIRS',
	'VRSS',
	'VRSG',
	'GRVT',
	'DRAY',
	'CRMC',
	'HEAC',
	'SAWD',
	'POLO',
	'RFRG',
	'RFGL',
	'LSNS',
	'LDTC',
	'SLCN',
	'PTNM',
	'VSNS',
	'ROCK',
	'LITH',
	'RSST',
	'RSSS',
	'BASE',
	'SEED',
	disabler(), # 196: reserved compatibility gap
	disabler(), # 197
	disabler(), # 198
	disabler(), # 199
	disabler(), # 200
	disabler(), # 201
	disabler(), # 202
	disabler(), # 203
	disabler(), # 204
	disabler(), # 205
	disabler(), # 206
	disabler(), # 207
	disabler(), # 208
	disabler(), # 209
	disabler(), # 210
	disabler(), # 211
	disabler(), # 212
	disabler(), # 213
	disabler(), # 214
	disabler(), # 215
	disabler(), # 216
	disabler(), # 217
	disabler(), # 218
	disabler(), # 219
	disabler(), # 220
	disabler(), # 221
	disabler(), # 222
	disabler(), # 223
	disabler(), # 224
	disabler(), # 225
	disabler(), # 226
	disabler(), # 227
	disabler(), # 228
	disabler(), # 229
	disabler(), # 230
	disabler(), # 231
	disabler(), # 232
	disabler(), # 233
	disabler(), # 234
	disabler(), # 235
	disabler(), # 236
	disabler(), # 237
	disabler(), # 238
	disabler(), # 239
	disabler(), # 240
	disabler(), # 241
	disabler(), # 242
	disabler(), # 243
	disabler(), # 244
	disabler(), # 245
	disabler(), # 246
	disabler(), # 247
	disabler(), # 248
	disabler(), # 249
	disabler(), # 250
	disabler(), # 251
	disabler(), # 252
	disabler(), # 253
	disabler(), # 254
	disabler(), # 255: reserved compatibility gap
	'ALUM', # 256: metallurgy
	'COPR', # 257
	'LEAD', # 258
	'TIN',  # 259
	'NICL', # 260
	'MAGN', # 261
	'CHRM', # 262
	'COBT', # 263
	'MOLY', # 264
	'ZINC', # 265
	'CHRC', # 266
	'COKE', # 267
	'STEL', # 268
	'BRNZ', # 269
	'BRAS', # 270
	'SSIL', # 271
	'NCRM', # 272
	'ALMG', # 273
	'TSTL', # 274
	'SLAG', # 275
	'FLUX', # 276
	'CRUC', # 277
	'MSCR', # 278
]

simulation_elem_src = []
simulation_elem_ids = []
elem_id = 0
foreach elem_name : simulation_elem_names
	if not is_disabler(elem_name)
		simulation_elem_src += elem_name + '.cpp'
		simulation_elem_ids += [ [ elem_name, elem_id ] ]
	endif
	elem_id = elem_id + 1
endforeach
simulation_files += files(simulation_elem_src)
