simulation_elem_names = [
	'NONE',
	'DUST',
	'WATR',
	'OIL',
	'FIRE',
	'STNE',
	'LAVA',
	'GUNP',
	'NITR',
	'CLNE',
	'GAS',
	'PLEX',
	'GOO',
	'ICEI',
	'METL',
	'SPRK',
	'SNOW',
	'WOOD',
	'NEUT',
	'PLUT',
	'PLNT',
	'ACID',
	'VOID',
	'WTRV',
	'CNCT',
	'DSTW',
	'SALT',
	'SLTW',
	'DMND',
	'BMTL',
	'BRMT',
	'PHOT',
	'URAN',
	'WAX',
	'MWAX',
	'PSCN',
	'NSCN',
	'LNTG',
	'INSL',
	'BHOL',
	'WHOL',
	'RBDM',
	'LRBD',
	'NTCT',
	'SAND',
	'GLAS',
	'PTCT',
	'BGLA',
	'THDR',
	'PLSM',
	'ETRD',
	'NICE',
	'NBLE',
	'BTRY',
	'LCRY',
	'STKM',
	'SWCH',
	'SMKE',
	'DESL',
	'COAL',
	'LO2',
	'O2',
	'INWR',
	'YEST',
	'DYST',
	'THRM',
	'GLOW',
	'BRCK',
	'CFLM',
	'FIRW',
	'FUSE',
	'FSEP',
	'AMTR',
	'BCOL',
	'PCLN',
	'HSWC',
	'IRON',
	'MORT',
	'LIFE',
	'DLAY',
	'CO2',
	'DRIC',
	'CBNW',
	'STOR',
	'PVOD',
	'CONV',
	'CAUS',
	'LIGH',
	'TESC',
	'DEST',
	'SPNG',
	'RIME',
	'FOG',
	'BCLN',
	'LOVE',
	'DEUT',
	'WARP',
	'PUMP',
	'FWRK',
	'PIPE',
	'FRZZ',
	'FRZW',
	'GRAV',
	'BIZR',
	'BIZRG',
	'BIZRS',
	'INST',
	'ISOZ',
	'ISZS',
	'PRTI',
	'PRTO',
	'PSTE',
	'PSTS',
	'ANAR',
	'VINE',
	'INVIS',
	'E116',
	'SPAWN2',
	'SPAWN',
	'SHLD1',
	'SHLD2',
	'SHLD3',
	'SHLD4',
	'LOLZ',
	'WIFI',
	'FILT',
	'ARAY',
	'BRAY',
	'STKM2',
	'BOMB',
	'C5',
	'SING',
	'QRTZ',
	'PQRT',
	'EMP',
	'BREC',
	'ELEC',
	'ACEL',
	'DCEL',
	'BANG',
	'IGNT',
	'BOYL',
	'GEL',
	'TRON',
	'TTAN',
	'EXOT',
	disabler(),
	'EMBR',
	'H2',
	'SOAP',
	'NBHL',
	'NWHL',
	'MERC',
	'PBCN',
	'GPMP',
	'CLST',
	'WIRE',
	'GBMB',
	'FIGH',
	'FRAY',
	'RPEL',
	'PPIP',
	'DTEC',
	'DMG',
	'TSNS',
	'VIBR',
	'BVBR',
	'CRAY',
	'PSTN',
	'FRME',
	'GOLD',
	'TUNG',
	'PSNS',
	'PROT',
	'VIRS',
	'VRSS',
	'VRSG',
	'GRVT',
	'DRAY',
	'CRMC',
	'HEAC',
	'SAWD',
	'POLO',
	'RFRG',
	'RFGL',
	'LSNS',
	'LDTC',
	'SLCN',
	'PTNM',
	'VSNS',
	'ROCK',
	'LITH',
	'RSST',
	'RSSS',
	'BASE',
	'SEED',
	disabler(), # 196: reserved compatibility gap
	disabler(), # 197
	disabler(), # 198
	disabler(), # 199
	disabler(), # 200
	disabler(), # 201
	disabler(), # 202
	disabler(), # 203
	disabler(), # 204
	disabler(), # 205
	disabler(), # 206
	disabler(), # 207
	disabler(), # 208
	disabler(), # 209
	disabler(), # 210
	disabler(), # 211
	disabler(), # 212
	disabler(), # 213
	disabler(), # 214
	disabler(), # 215
	disabler(), # 216
	disabler(), # 217
	disabler(), # 218
	disabler(), # 219
	disabler(), # 220
	disabler(), # 221
	disabler(), # 222
	disabler(), # 223
	disabler(), # 224
	disabler(), # 225
	disabler(), # 226
	disabler(), # 227
	disabler(), # 228
	disabler(), # 229
	disabler(), # 230
	disabler(), # 231
	disabler(), # 232
	disabler(), # 233
	disabler(), # 234
	disabler(), # 235
	disabler(), # 236
	disabler(), # 237
	disabler(), # 238
	disabler(), # 239
	disabler(), # 240
	disabler(), # 241
	disabler(), # 242
	disabler(), # 243
	disabler(), # 244
	disabler(), # 245
	disabler(), # 246
	disabler(), # 247
	disabler(), # 248
	disabler(), # 249
	disabler(), # 250
	disabler(), # 251
	disabler(), # 252
	disabler(), # 253
	disabler(), # 254
	disabler(), # 255: reserved compatibility gap
	'ALUM', # 256: metallurgy
	'COPR', # 257
	'LEAD', # 258
	'TIN',  # 259
	'NICL', # 260
	'MAGN', # 261
	'CHRM', # 262
	'COBT', # 263
	'MOLY', # 264
	'ZINC', # 265
	'CHRC', # 266
	'COKE', # 267
	'STEL', # 268
	'BRNZ', # 269
	'BRAS', # 270
	'SSIL', # 271
	'NCRM', # 272
	'ALMG', # 273
	'TSTL', # 274
	'SLAG', # 275
	'FLUX', # 276
	'CRUC', # 277
	'MSCR', # 278
	disabler(), # 279: metallurgy reserve
	disabler(), # 280
	disabler(), # 281
	disabler(), # 282
	disabler(), # 283
	disabler(), # 284
	disabler(), # 285
	disabler(), # 286
	disabler(), # 287
	'NUTR', # 288: biology
	'ALGA', # 289
	'MYCL', # 290
	'SPOR', # 291
	'PATH', # 292
	'STER', # 293
	'HUMS', # 294
	'BIOF', # 295
	disabler(), # 296
	disabler(), # 297
	disabler(), # 298
	disabler(), # 299
	disabler(), # 300
	disabler(), # 301
	disabler(), # 302
	disabler(), # 303
	disabler(), # 304
	disabler(), # 305
	disabler(), # 306
	disabler(), # 307
	disabler(), # 308
	disabler(), # 309
	disabler(), # 310
	disabler(), # 311
	disabler(), # 312
	disabler(), # 313
	disabler(), # 314
	disabler(), # 315
	disabler(), # 316
	disabler(), # 317
	disabler(), # 318
	disabler(), # 319
	disabler(), # 320
	disabler(), # 321
	disabler(), # 322
	disabler(), # 323
	disabler(), # 324
	disabler(), # 325
	disabler(), # 326
	disabler(), # 327
	'NFUL', # 328: advanced nuclear
	'MODR', # 329
	'CROD', # 330
	'NCLT', # 331
	'NWST', # 332
	'NGEN', # 333
	'RSHD', # 334
	disabler(), # 335
	disabler(), # 336
	disabler(), # 337
	disabler(), # 338
	disabler(), # 339
	disabler(), # 340
	disabler(), # 341
	disabler(), # 342
	disabler(), # 343
	disabler(), # 344
	disabler(), # 345
	disabler(), # 346
	disabler(), # 347
	disabler(), # 348
	disabler(), # 349
	disabler(), # 350
	disabler(), # 351
	disabler(), # 352
	disabler(), # 353
	disabler(), # 354
	disabler(), # 355
	disabler(), # 356
	disabler(), # 357
	disabler(), # 358
	disabler(), # 359
	'CHLR', # 360: chemistry
	'AMON', # 361
	'ETHL', # 362
	'KERO', # 363
	'GASO', # 364
	'ACTY', # 365
	'CATA', # 366
	'POLY', # 367
	'PERO', # 368
	'FERT', # 369
	'HE',   # 370: periodic He
	'BE',   # 371: periodic Be
	'B',    # 372: periodic B
	'N',   # 373: periodic N
	'F',   # 374: periodic F
	'NE',   # 375: periodic Ne
	'NA',   # 376: periodic Na
	'P',   # 377: periodic P
	'S',   # 378: periodic S
	'AR',   # 379: periodic Ar
	'K',    # 380: periodic K
	'CA',   # 381: periodic Ca
	'SC',   # 382: periodic Sc
	'V',    # 383: periodic V
	'MN',   # 384: periodic Mn
	'GA',   # 385: periodic Ga
	'GE',   # 386: periodic Ge
	'AS',   # 387: periodic As
	'SE',   # 388: periodic Se
	'BR',   # 389: periodic Br
	'KR',   # 390: periodic Kr
	'SR',   # 391: periodic Sr
	'Y',    # 392: periodic Y
	'ZR',   # 393: periodic Zr
	'NB',   # 394: periodic Nb
	'TC',   # 395: periodic Tc
	'RU',   # 396: periodic Ru
	'RH',   # 397: periodic Rh
	'PD',   # 398: periodic Pd
	'AG',   # 399: periodic Ag
	'CD',   # 400: periodic Cd
	'IN',   # 401: periodic In
	'SB',   # 402: periodic Sb
	'TE',   # 403: periodic Te
	'I',   # 404: periodic I
	'XE',   # 405: periodic Xe
	'CS',   # 406: periodic Cs
	'BA',   # 407: periodic Ba
	'LA',   # 408: periodic La
	'CE',   # 409: periodic Ce
	'PR',   # 410: periodic Pr
	'ND',   # 411: periodic Nd
	'PM',   # 412: periodic Pm
	'SM',   # 413: periodic Sm
	'EU',   # 414: periodic Eu
	'GD',   # 415: periodic Gd
	'TB',   # 416: periodic Tb
	'DY',   # 417: periodic Dy
	'HO',   # 418: periodic Ho
	'ER',   # 419: periodic Er
	'TM',   # 420: periodic Tm
	'YB',   # 421: periodic Yb
	'LU',   # 422: periodic Lu
	'HF',   # 423: periodic Hf
	'TA',   # 424: periodic Ta
	'RE',   # 425: periodic Re
	'OS',   # 426: periodic Os
	'IR',   # 427: periodic Ir
	'TL',   # 428: periodic Tl
	'BI',   # 429: periodic Bi
	'AT',   # 430: periodic At
	'RN',   # 431: periodic Rn
	'FR',   # 432: periodic Fr
	'RA',   # 433: periodic Ra
	'AC',   # 434: periodic Ac
	'TH',   # 435: periodic Th
	'PA',   # 436: periodic Pa
	'NP',   # 437: periodic Np
	'AM',   # 438: periodic Am
	'CM',   # 439: periodic Cm
	'BK',   # 440: periodic Bk
	'CF',   # 441: periodic Cf
	'ES',   # 442: periodic Es
	'FM',   # 443: periodic Fm
	'MD',   # 444: periodic Md
	'NO',   # 445: periodic No
	'LR',   # 446: periodic Lr
	'RF',   # 447: periodic Rf
	'DB',   # 448: periodic Db
	'SG',   # 449: periodic Sg
	'BH',   # 450: periodic Bh
	'HS',   # 451: periodic Hs
	'MT',   # 452: periodic Mt
	'DS',   # 453: periodic Ds
	'RG',   # 454: periodic Rg
	'CN',   # 455: periodic Cn
	'NH',   # 456: periodic Nh
	'FL',   # 457: periodic Fl
	'MC',   # 458: periodic Mc
	'LV',   # 459: periodic Lv
	'TS',   # 460: periodic Ts
	'OG',   # 461: periodic Og
	'HCLA', # 462: inorganic hydrochloric acid
	'SULA', # 463: inorganic sulfuric acid
	'NITA', # 464: inorganic nitric acid
	'PHOA', # 465: inorganic phosphoric acid
	'HYFA', # 466: inorganic hydrofluoric acid
	'NAOH', # 467: inorganic sodium hydroxide
	'KOH',  # 468: inorganic potassium hydroxide
	'CAOH', # 469: inorganic calcium hydroxide
	'KNIT', # 470: inorganic potassium nitrate
	'CUSF', # 471: inorganic copper sulfate
	'CACO', # 472: inorganic calcium carbonate
	'NABC', # 473: inorganic sodium bicarbonate
	'COMO', # 474: inorganic carbon monoxide
	'SODI', # 475: inorganic sulfur dioxide
	'NODI', # 476: inorganic nitrogen dioxide
	'CAOX', # 477: inorganic calcium oxide
	'CARA', # 478: inorganic carbonic acid
	'H2SG', # 479: inorganic hydrogen sulfide
	'AMWA', # 480: inorganic ammonia water
	'BAOH', # 481: inorganic barium hydroxide
	'KCL',  # 482: inorganic potassium chloride
	'CACL', # 483: inorganic calcium chloride
	'FECL', # 484: inorganic iron chloride
	'NASF', # 485: inorganic sodium sulfate
	'AMNT', # 486: inorganic ammonium nitrate
	'NACO', # 487: inorganic sodium carbonate
	'KPER', # 488: inorganic potassium permanganate
	'ALOX', # 489: inorganic aluminium oxide
	'MGOX', # 490: inorganic magnesium oxide
	'FEOX', # 491: inorganic iron oxide
	'CUOX', # 492: inorganic copper oxide
	'ZNOX', # 493: inorganic zinc oxide
	'SUTR', # 494: inorganic sulfur trioxide
	'NIMO', # 495: inorganic nitric oxide
	'TIOX', # 496: inorganic titanium dioxide
	'UROX', # 497: inorganic uranium oxide
	'CAPH', # 498: inorganic calcium phosphate
	'FESF', # 499: inorganic iron sulfide
	'NASD', # 500: inorganic sodium sulfide
	'HYCN', # 501: inorganic hydrogen cyanide
	'CACB', # 502: inorganic calcium carbide
	'SICB', # 503: inorganic silicon carbide
	'BORN', # 504: inorganic boron nitride
	'SINT', # 505: inorganic silicon nitride
	'NAHY', # 506: inorganic sodium hydride
	'CAHY', # 507: inorganic calcium hydride
	'ALCL', # 508: inorganic aluminium chloride
	'MGCL', # 509: inorganic magnesium chloride
	'CUCL', # 510: inorganic copper chloride
	'AMCL', # 511: inorganic ammonium chloride
	'SOLD', # 512: engineering tin-lead solder
	'CSTI', # 513: engineering cast iron
	'CUNI', # 514: engineering cupronickel
	'TIAL', # 515: engineering titanium alloy
	'NSAL', # 516: engineering nickel superalloy
	'WALY', # 517: engineering tungsten heavy alloy
	'ZRAL', # 518: engineering zirconium alloy
	'CNST', # 519: engineering constantan
	'NITI', # 520: engineering nickel-titanium shape-memory alloy
	'GYPS', # 521: gypsum
	'BAUX', # 522: bauxite
	'CUOR', # 523: copper ore
	'ZNOR', # 524: zinc ore
	'PBOR', # 525: lead ore
	'UORE', # 526: uranium ore
	'FELD', # 527: feldspar
	'CEMT', # 528: cement
	'ALCR', # 529: alumina ceramic
	'BSGL', # 530: borosilicate glass
	'QGLS', # 531: quartz glass
	'RFBK', # 532: refractory brick
	disabler(), # 533: reserved engineering material
	disabler(), # 534: reserved engineering material
	disabler(), # 535: reserved engineering material
	disabler(), # 536: reserved engineering material
	disabler(), # 537: reserved engineering material
	disabler(), # 538: reserved engineering material
	disabler(), # 539: reserved engineering material
	disabler(), # 540: reserved engineering material
	disabler(), # 541: reserved engineering material
	disabler(), # 542: reserved engineering material
	disabler(), # 543: reserved engineering material
	disabler(), # 544: reserved engineering material
	disabler(), # 545: reserved engineering material
	disabler(), # 546: reserved engineering material
	disabler(), # 547: reserved engineering material
	disabler(), # 548: reserved engineering material
	disabler(), # 549: reserved engineering material
	disabler(), # 550: reserved engineering material
	disabler(), # 551: reserved engineering material
	disabler(), # 552: reserved engineering material
	disabler(), # 553: reserved engineering material
	disabler(), # 554: reserved engineering material
	disabler(), # 555: reserved engineering material
	disabler(), # 556: reserved engineering material
	disabler(), # 557: reserved engineering material
	disabler(), # 558: reserved engineering material
	disabler(), # 559: reserved engineering material
	disabler(), # 560: reserved engineering material
	disabler(), # 561: reserved engineering material
	disabler(), # 562: reserved engineering material
	disabler(), # 563: reserved engineering material
	disabler(), # 564: reserved engineering material
	disabler(), # 565: reserved engineering material
	disabler(), # 566: reserved engineering material
	disabler(), # 567: reserved engineering material
	disabler(), # 568: reserved engineering material
	disabler(), # 569: reserved engineering material
	disabler(), # 570: reserved engineering material
	disabler(), # 571: reserved engineering material
	disabler(), # 572: reserved engineering material
	disabler(), # 573: reserved engineering material
	disabler(), # 574: reserved engineering material
	disabler(), # 575: reserved engineering material
	'H2IS', # 576: hydrogen-2 isotope
	'H3IS', # 577: hydrogen-3 isotope
	'C14I', # 578: carbon-14 isotope
	'CO60', # 579: cobalt-60 isotope
	'SR90', # 580: strontium-90 isotope
	'I131', # 581: iodine-131 isotope
	'CS37', # 582: caesium-137 isotope
	'TH32', # 583: thorium-232 isotope
	'U235', # 584: uranium-235 isotope
	'U238', # 585: uranium-238 isotope
	'PU39', # 586: plutonium-239 isotope
	'AM41', # 587: americium-241 isotope
	'CF52', # 588: californium-252 isotope
	'CH4M', # 589: methane
	'ETHA', # 590: ethane
	'PROP', # 591: propane
	'BUTA', # 592: butane
	'ETHE', # 593: ethylene
	'METH', # 594: methanol
	'ACET', # 595: acetone
	'BENZ', # 596: benzene
	'TOLU', # 597: toluene
	'GLYC', # 598: glycerol
	'ACTA', # 599: acetic acid
	'UREA', # 600: urea
	'FATS', # 601: fats and oils
	'GLUC', # 602: glucose
	'STRC', # 603: starch
	'CELU', # 604: cellulose
	'PRPE', # 605: propylene
	'BDIE', # 606: butadiene
	'VCHL', # 607: vinyl chloride
	'STYR', # 608: styrene
	'TFET', # 609: tetrafluoroethylene
	'ADIP', # 610: adipic acid
	'DIAM', # 611: diamine
	'ERES', # 612: uncured epoxy resin
	'PPLY', # 613: polypropylene
	'PVCL', # 614: polyvinyl chloride
	'PSTY', # 615: polystyrene
	'NYLN', # 616: nylon
	'RUBR', # 617: rubber
	'EPXY', # 618: cured epoxy
	'PTFE', # 619: polytetrafluoroethylene
	'BITM', # 620: bitumen
	'EACT', # 621: ethyl acetate
	'GAAS', # 622: gallium arsenide
	'GANI', # 623: gallium nitride
	'FRIT', # 624: ferrite
	'PMAG', # 625: permanent magnet material
	'SMAG', # 626: soft magnetic material
	'PZCR', # 627: piezoelectric ceramic
	'TELC', # 628: thermoelectric material
	'SUPC', # 629: superconducting ceramic
	'GRPH', # 630: graphene
	'CNTB', # 631: carbon nanotube material
	'AERG', # 632: aerogel
	'CFRP', # 633: carbon-fibre composite
	'LCOB', # 634: lithium cobalt oxide cathode
	'GRAN', # 635: graphite anode
	'SELE', # 636: solid electrolyte
	'ITOX', # 637: indium tin oxide
	'PCMT', # 638: phase-change memory material
	'ECHR', # 639: electrochromic material
	'PHRS', # 640: photoresist
	'DIEL', # 641: high-k dielectric ceramic
	disabler(), # 642: reserved electronic material
	disabler(), # 643: reserved electronic material
	disabler(), # 644: reserved electronic material
	disabler(), # 645: reserved electronic material
	disabler(), # 646: reserved electronic material
	disabler(), # 647: reserved electronic material
	disabler(), # 648: reserved electronic material
	disabler(), # 649: reserved electronic material
	disabler(), # 650: reserved electronic material
	disabler(), # 651: reserved electronic material
	disabler(), # 652: reserved electronic material
	disabler(), # 653: reserved electronic material
	disabler(), # 654: reserved electronic material
	disabler(), # 655: reserved electronic material
	disabler(), # 656: reserved electronic material
	disabler(), # 657: reserved electronic material
	disabler(), # 658: reserved electronic material
	disabler(), # 659: reserved electronic material
	disabler(), # 660: reserved electronic material
	disabler(), # 661: reserved electronic material
	disabler(), # 662: reserved electronic material
	disabler(), # 663: reserved electronic material
	disabler(), # 664: reserved electronic material
	disabler(), # 665: reserved electronic material
	disabler(), # 666: reserved electronic material
	disabler(), # 667: reserved electronic material
	disabler(), # 668: reserved electronic material
	disabler(), # 669: reserved electronic material
	'SOIL', # 670: soil
	'WWTR', # 671: wastewater
	'PEST', # 672: pesticide
	'HMET', # 673: heavy-metal contaminant
	'RCON', # 674: radioactive contaminant
	'MPLS', # 675: microplastic
	'OWST', # 676: organic waste
	'BLOM', # 677: algal bloom
	'MOLD', # 678: mould
	'BLOD', # 679: blood
	'TOXN', # 680: toxin
	'AMAT', # 681: antimicrobial material
	'SLUD', # 682: sludge
	'SMOG', # 683: smog
	'ARAN', # 684: acid rain
	'DETG', # 685: detergent
]

simulation_elem_src = []
simulation_elem_ids = []
elem_id = 0
foreach elem_name : simulation_elem_names
	if not is_disabler(elem_name)
		simulation_elem_src += elem_name + '.cpp'
		simulation_elem_ids += [ [ elem_name, elem_id ] ]
	endif
	elem_id = elem_id + 1
endforeach
simulation_files += files(simulation_elem_src)
