#!/usr/bin/env python3
"""Import and validate the bitmap font embedded in the i18n reference build.

The generated C++ resource remains part of the source build.  The reference
executable is read only by this reproducible import tool and is never executed.
"""

from __future__ import annotations

import argparse
import bz2
import hashlib
from pathlib import Path


EXPECTED_COMPRESSED_SHA256 = "c0213e00600e518f14db0304cf77293b2f2258c2e70577e9dea196ca00e8df87"
EXPECTED_DECOMPRESSED_SHA256 = "28fb742e864c7ee00eaa37ee7127ff7b8e2a507dabd1009fdccf49ebb39c6936"
EXPECTED_GLYPHS = 42385


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def extract_font(executable: Path) -> tuple[bytes, bytes]:
    image = executable.read_bytes()
    candidates: list[tuple[bytes, bytes]] = []
    start = 0
    while True:
        offset = image.find(b"BZh", start)
        if offset < 0:
            break
        decoder = bz2.BZ2Decompressor()
        try:
            decoded = decoder.decompress(image[offset:])
        except OSError:
            decoded = b""
        if decoder.eof:
            consumed = len(image[offset:]) - len(decoder.unused_data)
            compressed = image[offset : offset + consumed]
            if sha256(compressed) == EXPECTED_COMPRESSED_SHA256:
                candidates.append((compressed, decoded))
        start = offset + 3

    if len(candidates) != 1:
        raise RuntimeError(f"expected one verified font stream, found {len(candidates)}")
    compressed, decoded = candidates[0]
    if sha256(decoded) != EXPECTED_DECOMPRESSED_SHA256:
        raise RuntimeError("verified compressed stream has unexpected decoded hash")
    return compressed, decoded


def validate_glyph_stream(decoded: bytes) -> None:
    offset = 0
    previous = -1
    glyphs = 0
    while offset < len(decoded):
        if offset + 4 > len(decoded):
            raise RuntimeError("truncated glyph record")
        codepoint = decoded[offset] | decoded[offset + 1] << 8 | decoded[offset + 2] << 16
        width = decoded[offset + 3]
        record_size = 4 + width * 3  # 12 rows at four 2-bit pixels per byte
        if codepoint <= previous or codepoint >= 0x110000 or width > 64:
            raise RuntimeError(f"invalid glyph header at byte {offset}")
        if offset + record_size > len(decoded):
            raise RuntimeError(f"truncated glyph pixels at byte {offset}")
        previous = codepoint
        offset += record_size
        glyphs += 1
    if glyphs != EXPECTED_GLYPHS:
        raise RuntimeError(f"expected {EXPECTED_GLYPHS} glyphs, found {glyphs}")


def write_cpp(destination: Path, compressed: bytes) -> None:
    rows = []
    for offset in range(0, len(compressed), 24):
        rows.append("\t" + ", ".join(str(value) for value in compressed[offset : offset + 24]))
    body = ",\n".join(rows)
    destination.write_text(
        '#include "font_bz2.h"\n\n'
        "// Generated by tools/import_reference_font.py from the statically verified\n"
        "// Windows i18n reference font. Do not edit this byte array by hand.\n"
        f"const struct font_bz2Resource font_bz2 = {{{{{{\n{body}\n}}}}}};\n",
        encoding="utf-8",
        newline="\n",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("reference_exe", type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "src/graphics/font_bz2.cpp",
    )
    args = parser.parse_args()
    compressed, decoded = extract_font(args.reference_exe)
    validate_glyph_stream(decoded)
    write_cpp(args.output, compressed)
    print(
        f"imported {EXPECTED_GLYPHS} glyphs; compressed={len(compressed)} "
        f"sha256={sha256(compressed)}"
    )


if __name__ == "__main__":
    main()
